# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

node_modules_path = '../node_modules'
react_path = File.join(node_modules_path, 'react-native')
yoga_path = File.join(react_path, 'ReactCommon/yoga')
sentry_path = File.join(node_modules_path, 'react-native-sentry')

target 'DePunaise' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'yoga', :path => yoga_path
  pod 'React', :path => react_path, :subspecs => [
    'Core',
    'BatchedBridge',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'DevSupport'
  ]

  pod 'SentryReactNative', :path => sentry_path

  # Required by RNFirebase
  pod 'Firebase/Core'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/Auth'
  pod 'Firebase/Performance'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'

  # pod 'Firebase/AdMob'
  # pod 'Firebase/Crash'
  # pod 'Firebase/Database'
  # pod 'Firebase/DynamicLinks'
  # pod 'Firebase/Firestore'
  # pod 'Firebase/Storage'

  # pod 'Fabric', '~> 1.7.2'
  # pod 'Crashlytics', '~> 3.9.3'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-mail', :path => '../node_modules/react-native-mail'
  pod 'react-native-webgl', :path => '../node_modules/react-native-webgl'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
